ARG BUILD_IMAGE=ubuntu:20.04
ARG DEPLOY_IMAGE=ubuntu:20.04

FROM $BUILD_IMAGE AS builder

ARG BUILD_DATE=1970-01-01T00:00:00Z
ARG BUILD_COMMIT=unknown
ARG FFMPEG_VERSION=none

ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
ENV SRC=/usr/local
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
  apt-get install -y \
  pkg-config \
  curl \
  git \
  nasm \
  openssl \
  libssl-dev \
  cmake \
  automake \
  meson \
  yasm \
  build-essential \
  libtool \
  autoconf \
  xorg \
  xorg-dev \
  openbox \
  libx11-dev \
  libgl1 \
  libglx-mesa0 \
  libdrm-dev \
  libv4l-dev \
  libva-drm2 \
  libva2 \
  libva-dev \
  i965-va-driver-shaders \
  intel-media-va-driver-non-free \
  libasound2-dev \
  libx264-dev \
  libx265-dev \
  librav1e-dev \
  libaom-dev \
  libdav1d-dev \
  libvpx-dev \
  libmp3lame-dev \
  libopus-dev \
  libvorbis-dev \
  libogg-dev \
  libfreetype-dev \
  libsrt-openssl-dev \
  libxml2-dev \
  libfdk-aac-dev \
  libharfbuzz-dev \
  libxml2-dev \
  libxcb1-dev \
  libxcb-xfixes0-dev \
  libxcb-shm0-dev \
  libxcb-shape0-dev \
  zlib1g-dev

# Build the newest libva
RUN git clone https://github.com/intel/libva.git /tmp/libva && \
    cd /tmp/libva && \
    ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu && \
    make -j$(nproc) && \
    make install

# Build the newest gmmlib (dependency for media-driver)
RUN git clone https://github.com/intel/gmmlib.git /tmp/gmmlib && \
    cd /tmp/gmmlib && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_INSTALL_LIBDIR=/usr/lib/x86_64-linux-gnu \
          -DCMAKE_BUILD_TYPE=ReleaseInternal .. && \
    make -j$(nproc) && \
    make install

# Build the newest media-driver
RUN git clone https://github.com/intel/media-driver.git /tmp/media-driver && \
    cd /tmp/media-driver && \
    mkdir build_media && cd build_media && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_INSTALL_LIBDIR=/usr/lib/x86_64-linux-gnu \
          ../ && \
    make -j$(nproc) && \
    make install

# install and patch ffmpeg
RUN mkdir -p /dist && cd /dist && \
  curl -OLk http://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz && \
  tar -xvz -f ffmpeg-${FFMPEG_VERSION}.tar.gz && \
  rm ffmpeg-${FFMPEG_VERSION}.tar.gz

COPY ./contrib /contrib

RUN cd /dist/ffmpeg-${FFMPEG_VERSION} && \
  patch -p1 < /contrib/ffmpeg-jsonstats.patch && \
  patch -p1 < /contrib/ffmpeg-hls.patch && \
  ./configure \
  --extra-version="datarhei-${BUILD_COMMIT}-${BUILD_DATE}" \
  --prefix="${SRC}" \
  --enable-nonfree \
  --enable-gpl \
  --enable-version3 \
  --enable-postproc \
  --enable-static \
  --enable-openssl \
  --enable-libxml2 \
  --enable-vaapi \
  --enable-libv4l2 \
  --enable-libfreetype \
  --enable-alsa \
  --enable-libsrt \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libvpx \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libvorbis \
  --enable-libfdk-aac \
  --enable-libdav1d \
  --enable-librav1e \
  --enable-libaom \
  --enable-libxcb \
  --disable-ffplay \
  --disable-ffprobe \
  --disable-debug \
  --disable-doc && \
  make -j$(nproc) && \
  make install && \
  hash -r

RUN mkdir -p /ffmpeglibs && \
  ldd /usr/local/bin/ffmpeg | grep -o -e '/lib/[a-z0-9_]*-linux-gnu/[^ ]*' | xargs -I % cp -v % /ffmpeglibs

FROM $DEPLOY_IMAGE

COPY --from=builder /usr/local/bin/ffmpeg /usr/local/bin/ffmpeg
COPY --from=builder /ffmpeglibs /ffmpeglibs
COPY --from=builder /usr/lib/x86_64-linux-gnu usr/lib/x86_64-linux-gnu

ENV DEBIAN_FRONTEND=noninteractive
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
ENV LD_RUN_PATH=/usr/lib/x86_64-linux-gnu

RUN echo "/ffmpeglibs" > /etc/ld.so.conf.d/ffmpeg.conf && \
  ldconfig && \
  apt-get update && \
  apt-get install -y \
  ca-certificates \
  tzdata \
  v4l-utils \
  fbset \
  x265 \
  libssl3 \
  zlib1g \
  i965-va-driver-shaders \
  libasound2-dev && \
  ffmpeg -buildconf

WORKDIR /tmp
ENTRYPOINT ["/usr/local/bin/ffmpeg"]
CMD ["-version"]